/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import clases.almacenamientoUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class Registro extends javax.swing.JFrame {

    private final almacenamientoUsuario almacenamientoUsuario;

    /**
     * Constructor de la clase Registro. Inicializa la interfaz gráfica y la
     * instancia de almacenamientoUsuario.
     */
    public Registro() {
        initComponents();
        almacenamientoUsuario = new almacenamientoUsuario(); // Ajusta esto según tu implementación

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        EscribirUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Contraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnResgitro = new javax.swing.JButton();
        EscribirContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(253, 253, 231));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Register");

        jPanel4.setBackground(new java.awt.Color(253, 253, 231));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        Usuario.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Usuario.setText("Usuario :");

        EscribirUsuario.setForeground(new java.awt.Color(204, 204, 204));
        EscribirUsuario.setText("Ingrese un usuario");
        EscribirUsuario.setBorder(null);
        EscribirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirUsuarioMousePressed(evt);
            }
        });
        EscribirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(EscribirUsuario))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Usuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EscribirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/logoblanco40.jpg"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoMousePressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(253, 253, 231));

        Contraseña.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Contraseña.setText("Contraseña :");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnResgitro.setBackground(new java.awt.Color(253, 253, 231));
        btnResgitro.setText("Register");
        btnResgitro.setBorder(null);
        btnResgitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResgitroActionPerformed(evt);
            }
        });

        EscribirContra.setForeground(new java.awt.Color(204, 204, 204));
        EscribirContra.setText("********");
        EscribirContra.setBorder(null);
        EscribirContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscribirContraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResgitro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EscribirContra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraseña)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EscribirContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResgitro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Logo)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnResgitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResgitroActionPerformed
        // Código para el botón de registro
        String usuario = EscribirUsuario.getText();
        String contrasena = String.valueOf(EscribirContra.getPassword());

        // Validaciones de usuario y contraseña
        if (!usuario.isEmpty() && !contrasena.isEmpty()) {
            // Intentar registrar al usuario en la base de datos
            boolean registroExitoso = almacenamientoUsuario.registrarUsuario(usuario, contrasena);

            if (registroExitoso) {
                // Registro exitoso
                JOptionPane.showMessageDialog(this, "Usuario registrado con éxito", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                //Cerar ventana actual
                this.dispose();
                pantallaPrincipal pantallaprincipal = new pantallaPrincipal();
                pantallaprincipal.setVisible(true);
            } else {
                // Registro fallido
                JOptionPane.showMessageDialog(this, "Error al registrar usuario", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mensaje si el usuario o la contraseña están vacíos
            JOptionPane.showMessageDialog(this, "Por favor, complete el formulario", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnResgitroActionPerformed

    private void EscribirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirUsuarioActionPerformed

    private void EscribirUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirUsuarioMousePressed
        if (EscribirUsuario.getText().equals("Ingrese un usuario")) {
            EscribirUsuario.setText("");
            EscribirUsuario.setForeground(Color.black);
        }
        if (String.valueOf(EscribirContra.getPassword()).isEmpty()) {
            EscribirContra.setText("********");
            EscribirContra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_EscribirUsuarioMousePressed

    private void EscribirContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirContraMousePressed
        if (String.valueOf(EscribirContra.getPassword()).equals("********")) {
            EscribirContra.setText("");
            EscribirContra.setForeground(Color.black);
        }
        if (EscribirUsuario.getText().isEmpty()) {
            EscribirUsuario.setText("Ingrese su usuario");
            EscribirUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_EscribirContraMousePressed

    /**
     * Método que se ejecuta al hacer clic en el logo. Abre la pantalla
     * principal y cierra la ventana actual.
     *
     * @param evt Evento asociado al clic en el logo.
     */
    private void LogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMousePressed
        // Lógica para abrir la nueva pantalla (PantallaX)
        pantallaPrincipal pantallaprincipal = new pantallaPrincipal();
        pantallaprincipal.setVisible(true);

        // Opcional: cerrar la ventana actual si es necesario
        this.dispose();
    }//GEN-LAST:event_LogoMousePressed

    /**
     * Método principal que inicia la aplicación y muestra la interfaz gráfica
     * de registro.
     *
     * @param args Los argumentos de la línea de comandos (no se utilizan en
     * este caso).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField EscribirContra;
    private javax.swing.JTextField EscribirUsuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnResgitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
